# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT710 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "7.1.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.0/src-cli_7.1.0_darwin_amd64.tar.gz"
      sha256 "958d961032cd858d0e250143754853fe44c0c3cb972bfdda6e2aea4aaa5c0a61"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.0/src-cli_7.1.0_darwin_arm64.tar.gz"
      sha256 "396829b6694576f18f7782bf107e1ae1b53a5d7480fa7d373cc23c612c6c7470"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.0/src-cli_7.1.0_linux_amd64.tar.gz"
        sha256 "2f5a73395db7bdc2816485547f5d2660ac04f567123f69a84a66132e64d5ca6f"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.0/src-cli_7.1.0_linux_arm64.tar.gz"
        sha256 "d2a50f5d95b837367643db9116fa4b6f028f59008dc48ec0b8b4de1b13d0f858"

        def install
          bin.install "src"
        end
      end
    end
  end
end
