# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT713 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "7.1.3"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.3/src-cli_7.1.3_darwin_amd64.tar.gz"
      sha256 "82fdbdf4af9370e651228cc2a67a70dd7e49c11da229e3b22187e451f6e6fb73"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.3/src-cli_7.1.3_darwin_arm64.tar.gz"
      sha256 "e905db08bb97ac4d2a309fa217397c0988fbb967a095251088847b1ed6e42f39"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.3/src-cli_7.1.3_linux_amd64.tar.gz"
        sha256 "ce5dfcc20eead64db932997c113cd96ee48bfa2bf9662a6e85d8fbaac736e630"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.3/src-cli_7.1.3_linux_arm64.tar.gz"
        sha256 "5e01089bdb02874fda07b3fadcff79809073f5c63a362b45a8c4f16b93ca4862"

        def install
          bin.install "src"
        end
      end
    end
  end
end
