# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT441 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "4.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.4.1/src-cli_4.4.1_darwin_arm64.tar.gz"
      sha256 "099eda183941098de5d78fa92515e7c2307aecd5a70416326beaae5ab12399ed"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.4.1/src-cli_4.4.1_darwin_amd64.tar.gz"
      sha256 "0f2afdafe031c982e225f55acd5b25fcd9a7d70e9774d387d79dbb514e76809b"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.4.1/src-cli_4.4.1_linux_arm64.tar.gz"
      sha256 "3d77cce4963a6f817f56d58c0fbdb0c1d8b2df1eb0fb52d7a200127ccb4acccf"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.4.1/src-cli_4.4.1_linux_amd64.tar.gz"
      sha256 "b9b823b429581cd70ab5833384085dd8ef6d8d10c61c8cd319e7983eb3ede979"

      def install
        bin.install "src"
      end
    end
  end
end
