# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT6110 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.11.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.11.0/src-cli_6.11.0_darwin_amd64.tar.gz"
      sha256 "9d941257b3451e78932a7f4edb709f6ecd4a2184cb480119ee62677ea2b0e23d"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.11.0/src-cli_6.11.0_darwin_arm64.tar.gz"
      sha256 "c0a9760b7387519fa206d93f21b20d87430d7a1c9074c9fd5b2bcefe645df65f"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.11.0/src-cli_6.11.0_linux_amd64.tar.gz"
        sha256 "ecad50af944347897acaba461bba35393b7114538454ee12a58ca908acc2d7f7"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.11.0/src-cli_6.11.0_linux_arm64.tar.gz"
        sha256 "957d1d876633af1fc2ce07f6b0af723be04463143731e7b6ec6259999553d574"

        def install
          bin.install "src"
        end
      end
    end
  end
end
