# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT400 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "4.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.0/src-cli_4.0.0_darwin_arm64.tar.gz"
      sha256 "490088591e4177a91871353753bdda7592615f18ab78bafa71ffba26a02037ef"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.0/src-cli_4.0.0_darwin_amd64.tar.gz"
      sha256 "b3fb7f5ec8b1068b8afe2ab82866f8d573a7cee3c3c8adebe95bc9ca96ea0387"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.0/src-cli_4.0.0_linux_arm64.tar.gz"
      sha256 "1569e945301a9805f5f26fbbfeeff200326a2c10cc1e5c41fdd583d0b31d4044"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.0/src-cli_4.0.0_linux_amd64.tar.gz"
      sha256 "cffb4a07e98cba864a74ca259d9c33dced78bab4ad93e06627aad3d2d3ebf081"

      def install
        bin.install "src"
      end
    end
  end
end
