# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT712 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "7.1.2"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_darwin_amd64.tar.gz"
      sha256 "88e67563575eec55a791c630ab1d294e19ded6073a844bf26654a9354180f327"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_darwin_arm64.tar.gz"
      sha256 "29bc1611e0804e9765b50b03bfb2b56d6b0e40509b9275924a327309b01debaf"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_linux_amd64.tar.gz"
        sha256 "8f0bb5825d0c6eb18773dde060975dfad8613fb4787882ed7e169bf48f7226fc"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_linux_arm64.tar.gz"
        sha256 "86d5571d1dae7a438dd61028631e89d6657efb9f5ef5c37fb6083bce726495b7"

        def install
          bin.install "src"
        end
      end
    end
  end
end
