# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT520 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.2.0/src-cli_5.2.0_darwin_arm64.tar.gz"
      sha256 "69b2ef9de708e52696aa09541c4b134745f4bfee5180322bbf26858f57783e8c"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.2.0/src-cli_5.2.0_darwin_amd64.tar.gz"
      sha256 "57caaf76bb228fa9f8ea528123e59dffc5d88778dd26c9f8ba23ac834bb7f275"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.2.0/src-cli_5.2.0_linux_amd64.tar.gz"
      sha256 "9da68c8fcb8c86733d7aeeaae1fdcda028b6ae2abc726d2b95dc7edbdb8aae4e"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.2.0/src-cli_5.2.0_linux_arm64.tar.gz"
      sha256 "4fd7c1059c290220ade23ab18296611061bcf3a2202830b4aa9e8c2338b6a7ef"

      def install
        bin.install "src"
      end
    end
  end
end
