# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT690 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.9.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.9.0/src-cli_6.9.0_darwin_amd64.tar.gz"
      sha256 "37e4ecf37a479e85155137fe875168cbcf26cedf88b2cb03aba9496f1e8e3952"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.9.0/src-cli_6.9.0_darwin_arm64.tar.gz"
      sha256 "22f8ad2d84e8b86e62dd5b1b862db011d64bf9c97a7a571fd3875873d0ef75d1"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.9.0/src-cli_6.9.0_linux_amd64.tar.gz"
        sha256 "8e2e37daba5374405cda3d1c528680fb29b6fc69514ce60a87d7c01cf7561351"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.9.0/src-cli_6.9.0_linux_arm64.tar.gz"
        sha256 "ee9d732e11dbc7ff3a859feb975054a23988732714e4c7e9beee69f06ba66dba"

        def install
          bin.install "src"
        end
      end
    end
  end
end
