# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT6123 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.12.3"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_darwin_amd64.tar.gz"
      sha256 "3a6a1e0282dfb918ec513a0f6d09cced40f6c55103ac0f4c375cd595aede5580"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_darwin_arm64.tar.gz"
      sha256 "15c8bbe2014cee0d7b88e05992760285a2e8c74d78879822088684793bb41694"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_linux_amd64.tar.gz"
        sha256 "126a2ffdea9ea94c9f2e8fc784b5385466f4be86a05711a53d1384588678c7de"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_linux_arm64.tar.gz"
        sha256 "1762841e37ad8d97f840b09597f23b2781b2e5c84478f912b605b4ba44af0c1c"

        def install
          bin.install "src"
        end
      end
    end
  end
end
