# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT630 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.3.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.3.0/src-cli_6.3.0_darwin_amd64.tar.gz"
      sha256 "86de70c2625dea87c04743e13e1752a1140c0d3649ffc38311558da2e79ea433"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.3.0/src-cli_6.3.0_darwin_arm64.tar.gz"
      sha256 "761b4cb5e36c33086b7b1506846a881b4f58c39172135b2bdcad06d331d11ee6"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.3.0/src-cli_6.3.0_linux_amd64.tar.gz"
        sha256 "3957acc52739533135c91bab3c9f50210a11a844723d6d669a86f70fce405330"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.3.0/src-cli_6.3.0_linux_arm64.tar.gz"
        sha256 "d0678330d1bfe0cf6843d98d8e9aef34a4bb7ed466313c9b20174d4df5996f52"

        def install
          bin.install "src"
        end
      end
    end
  end
end
