# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT510 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.0/src-cli_5.1.0_darwin_amd64.tar.gz"
      sha256 "08a9e154826b489e3acb93a439b3746f4fa1e5022372989df5839f4c3be93d78"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.0/src-cli_5.1.0_darwin_arm64.tar.gz"
      sha256 "e70abac3ad04da9dde86c6095590f09203587277f24c00674e5b8cb08696cc00"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.0/src-cli_5.1.0_linux_arm64.tar.gz"
      sha256 "a4d0117df85fe3b8827c56bf4368c0ccc611a220d461f37cfb90a895d91c2653"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.0/src-cli_5.1.0_linux_amd64.tar.gz"
      sha256 "807a33cf8e3c1ee846f8e8d6f0d5d3a633a4acbee823d90128f21ea4e335085f"

      def install
        bin.install "src"
      end
    end
  end
end
