# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT401 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "4.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.1/src-cli_4.0.1_darwin_arm64.tar.gz"
      sha256 "e5dc52cb5597403e5090eb5b337ca38c7b01babfae984f69b8faae2a647953b0"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.1/src-cli_4.0.1_darwin_amd64.tar.gz"
      sha256 "21611728d9749b4e421060c8c0be70d85f36d1bac31be2dd48bd2659ad423cb2"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.1/src-cli_4.0.1_linux_arm64.tar.gz"
      sha256 "e99546a27e3d2143a8ec609c28747496b570a765998c1693cb5b2d7b532f531f"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.0.1/src-cli_4.0.1_linux_amd64.tar.gz"
      sha256 "b0648c8001df813d7ac6feedcbbbc126629bc288f16f03bdd308323dd18417f0"

      def install
        bin.install "src"
      end
    end
  end
end
