# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCli < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "3.14"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sourcegraph/src-cli/releases/download/3.14/src-cli_3.14_darwin_amd64.tar.gz"
    sha256 "984a5a0b978ba75b566271cb0012c5f04ca4a8e9ffe2ca0b674cb78efb0213e6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/3.14/src-cli_3.14_linux_amd64.tar.gz"
      sha256 "8862908ab9acaeff055a4ea821593c6f47e802d89d785e80eaf55747f4a02da1"
    end
  end

  def install
    bin.install "src"
  end
end
