# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT450 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "4.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.5.0/src-cli_4.5.0_darwin_amd64.tar.gz"
      sha256 "8f3e4892e924221633688d53e64c509f19fd64fb5d31bd56165a1c87b972a74a"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.5.0/src-cli_4.5.0_darwin_arm64.tar.gz"
      sha256 "61436fa145e549e3cdc41bf95c47963fc5294277f01c397b7fde767cf348a2a6"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.5.0/src-cli_4.5.0_linux_arm64.tar.gz"
      sha256 "ddae8bf9a08a79d95b41b6f25ee10dc2a8ecc774ea27c3a69f6f081a63388e16"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.5.0/src-cli_4.5.0_linux_amd64.tar.gz"
      sha256 "c2b57ccab802e173b9d71ffecbf08c93ef36a7cb25520bba769308af6e8362b3"

      def install
        bin.install "src"
      end
    end
  end
end
