# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT511 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.1/src-cli_5.1.1_darwin_arm64.tar.gz"
      sha256 "794d7ab07c31ace7d6f579c89195b754ac52ff2aea36a2abbff7a2a0add5287d"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.1/src-cli_5.1.1_darwin_amd64.tar.gz"
      sha256 "87f5f9d80c7423aeae82bd5b82dee631086c3bc1c8a1b471a315f9277f5d111f"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.1/src-cli_5.1.1_linux_arm64.tar.gz"
      sha256 "3090a2604d652b4a65744fb633272ab082fa183562b982932429309f90440128"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.1/src-cli_5.1.1_linux_amd64.tar.gz"
      sha256 "7f21d3b1591716736039e3b412def2b008c7d8fc9edc25a90dd5a6debfa012f3"

      def install
        bin.install "src"
      end
    end
  end
end
