# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT540 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.4.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_darwin_amd64.tar.gz"
      sha256 "ad5f13fbf63716c895ffc745e6247d7506feed1a8f120ee13742d516838b5474"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_darwin_arm64.tar.gz"
      sha256 "b507b490a46243679f9ed0d6711429ceb5995f23fadf23a856b5cbc38adafbbc"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_linux_amd64.tar.gz"
        sha256 "30973bab8258f49fd550e145ae2b398ef4cfbddc22716693d9360cab951dc5eb"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_linux_arm64.tar.gz"
        sha256 "e078924f71e9f7b51ea18eee265d3a7dbfb267f78c9fa255d12b23ffe830fde7"

        def install
          bin.install "src"
        end
      end
    end
  end
end
