# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT530 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.3.0/src-cli_5.3.0_darwin_arm64.tar.gz"
      sha256 "0e3e97ec9bb9fe8d4957ebf7886a20f60432612c2633b02075083e4da8733ce1"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.3.0/src-cli_5.3.0_darwin_amd64.tar.gz"
      sha256 "eace079086178d69766e8acce73017a2bba92511980704699aecc23b5e80136c"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.3.0/src-cli_5.3.0_linux_arm64.tar.gz"
      sha256 "aeb052f37af6de3456ab31b5606a8fe7eaa787bee424cfd76c9baa8c2ec51dc6"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.3.0/src-cli_5.3.0_linux_amd64.tar.gz"
      sha256 "fe8beaa97fe0ad77bad994edbf4b7687ec58ef986c59d78a2f2220669c06bd49"

      def install
        bin.install "src"
      end
    end
  end
end
