# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT6123 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.12.3"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_darwin_amd64.tar.gz"
      sha256 "07c72203e074a6849905ced186e167f6ca4f9072390ea8507b8d85bb90d71915"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_darwin_arm64.tar.gz"
      sha256 "03bb3d6a5603804af397520bd798aa11825b8c84f41ebd2624e9c25b7fbd8507"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_linux_amd64.tar.gz"
        sha256 "b9452fe3739325c7245dccba4d2893d6fa7db03aed2de1f813fa39f87daa8966"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.3/src-cli_6.12.3_linux_arm64.tar.gz"
        sha256 "9c4e01d9566dde8b16171cd33d2f6877b96a6373f48a6a151504b733de6cc208"

        def install
          bin.install "src"
        end
      end
    end
  end
end
