# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT580 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.8.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/5.8.0/src-cli_5.8.0_darwin_amd64.tar.gz"
      sha256 "35eb6340308882785389aee0465a6071b038b76fc39b6dc0e55fb59dd03f665c"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/5.8.0/src-cli_5.8.0_darwin_arm64.tar.gz"
      sha256 "6f88133278d3bd6e745a6999999f8e1890e081ae3134409bf2e298a8bf918c25"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/5.8.0/src-cli_5.8.0_linux_amd64.tar.gz"
        sha256 "09ca4d38575f83fb93bd7556ddd6edabe2a0e6ff7575ae2222e643f5e2032043"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/5.8.0/src-cli_5.8.0_linux_arm64.tar.gz"
        sha256 "64a8cbf55f6db2b522185d887699d6eb970519c9a065c6b2a085d1eab85737df"

        def install
          bin.install "src"
        end
      end
    end
  end
end
