# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT6122 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.12.2"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.2/src-cli_6.12.2_darwin_amd64.tar.gz"
      sha256 "b8c31689c334392a067ee1da5b553176f27fa54b84c3771503c807b71c3ae84c"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.2/src-cli_6.12.2_darwin_arm64.tar.gz"
      sha256 "b00d4b263a068b7af30480e4a0e83fe6f34a8afd20cc640f9bcce314213a5a88"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.2/src-cli_6.12.2_linux_amd64.tar.gz"
        sha256 "414db177a49bb38b621293fb9cccb66976f7fc15fcad79df7779fbb489f46ca0"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.2/src-cli_6.12.2_linux_arm64.tar.gz"
        sha256 "6212cb2bf7baea7c70fcc638560388e6c9827a27d4a5f83eb80d5d793ad08295"

        def install
          bin.install "src"
        end
      end
    end
  end
end
