# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT6100 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.10.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.10.0/src-cli_6.10.0_darwin_amd64.tar.gz"
      sha256 "82de9bf9ef4315385ee95dd64041708bc00e8afbb7109eb0d1e80ad1fe391fcd"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.10.0/src-cli_6.10.0_darwin_arm64.tar.gz"
      sha256 "6c41fe948c9ffbc93868b44d3661075649c1cc89fdee605e9f3cfe6a5a70e28f"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.10.0/src-cli_6.10.0_linux_amd64.tar.gz"
        sha256 "1193334ecf2506d230dd2b1a451ceb4563ca9fd8a0257b45ea2ac9dbf5a300be"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.10.0/src-cli_6.10.0_linux_arm64.tar.gz"
        sha256 "04b33fc92421266197a75afe6b88ee1e62ab744dda757057941d09b87ab85fcb"

        def install
          bin.install "src"
        end
      end
    end
  end
end
