# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT712 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "7.1.2"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_darwin_amd64.tar.gz"
      sha256 "653101e98a13632fc6170b76d5677bbfc6f4a882b2656bd0b431f22f28f2b65d"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_darwin_arm64.tar.gz"
      sha256 "b314763d86240aac681257f5deb439cc59b8e5ae453f01c8054b91a78ec997a0"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_linux_amd64.tar.gz"
        sha256 "3ea9017077ddb6b87401ac4d565a3686e79442ed8adb89c01c9f2f85599eb0ce"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.2/src-cli_7.1.2_linux_arm64.tar.gz"
        sha256 "61a63d8c030779356ebc84e4cb45fdc87eb7b9e9a6355af5783cde1d0c54131e"

        def install
          bin.install "src"
        end
      end
    end
  end
end
