# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT503 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.3/src-cli_5.0.3_darwin_arm64.tar.gz"
      sha256 "8013b2f3047512ae66a5d4132e70ee94a5839e2e6aee3385005577e028cea9fa"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.3/src-cli_5.0.3_darwin_amd64.tar.gz"
      sha256 "b7586f3126dcdfde914ba08d7676fdd0b21c4c3bf0d2d72d49387c44fcb46b7d"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.3/src-cli_5.0.3_linux_arm64.tar.gz"
      sha256 "2fb66acb2d8191ef8ceb205968fd340c1fb0977368e6842d79184603e18594ae"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.3/src-cli_5.0.3_linux_amd64.tar.gz"
      sha256 "d125d732ad4c47ae6977c49574b01cc1b3c943b2a2108142267438e829538aa3"

      def install
        bin.install "src"
      end
    end
  end
end
