# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT6121 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "6.12.1"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.1/src-cli_6.12.1_darwin_amd64.tar.gz"
      sha256 "1e8ff4667eeb1d1ef28bce7811ecc227e4df354d7d60176406c566dc063d07d6"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/6.12.1/src-cli_6.12.1_darwin_arm64.tar.gz"
      sha256 "795825139a7c893ca8167c3870c972dfe031cff10cd012ac85ff70bfb5a9032c"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.1/src-cli_6.12.1_linux_amd64.tar.gz"
        sha256 "19002d02d435e582ff85ee7248ca8101ac400890cb53201339e4cb995553a55b"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/6.12.1/src-cli_6.12.1_linux_arm64.tar.gz"
        sha256 "c9dfdff2290230928d2fb7ca3912a52b88ec8cffdb6f2b56e65917abbeaa3d85"

        def install
          bin.install "src"
        end
      end
    end
  end
end
