# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT540 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.4.0"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_darwin_amd64.tar.gz"
      sha256 "084df89a2956884e27b88473cfc5c70747cc4444b63db97fd0a450cf7e0fb199"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_darwin_arm64.tar.gz"
      sha256 "28a792947e871808a666c8e91fa7b62f246eb7bd718ff54f6be5f069263e659c"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_linux_amd64.tar.gz"
        sha256 "48db47cb0b92ad83d130ea91fd3e08cf84d6a70184e98d9f0321d100c6f48b6f"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/5.4.0/src-cli_5.4.0_linux_arm64.tar.gz"
        sha256 "ff62ad38d9deb6f02ad62cbb837f39d7b5b91cb6680dd0b80815820e136681fb"

        def install
          bin.install "src"
        end
      end
    end
  end
end
