# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT410 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "4.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.1.0/src-cli_4.1.0_darwin_arm64.tar.gz"
      sha256 "995a0d17b815da888c184901e0f7cafb3f55665fded6b771703a614b0b95c959"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.1.0/src-cli_4.1.0_darwin_amd64.tar.gz"
      sha256 "fe2f9c67d8390c224e5915b11784fd225933aa50db23ade9f265ee5f2cd9ffad"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.1.0/src-cli_4.1.0_linux_amd64.tar.gz"
      sha256 "f6e5e86c6f95500b02afb0a5211f42e3bb6e8b5ab31f45161bba10d7f0f5c51a"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/4.1.0/src-cli_4.1.0_linux_arm64.tar.gz"
      sha256 "089edb3e1d7debfdda64144b5e6902e74f8770cecbe1f7e210529707eea9a438"

      def install
        bin.install "src"
      end
    end
  end
end
