# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT720 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "7.2.1"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.2.1/src-cli_7.2.1_darwin_amd64.tar.gz"
      sha256 "9dc3d36e8d084cf056382c0b1c1ad40e2275aea5320ba79dcafab65112cae635"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.2.1/src-cli_7.2.1_darwin_arm64.tar.gz"
      sha256 "66ede465a6e94a2435ad20abe7c6445db9cef9fe4c093afae5b7d25350964feb"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.2.1/src-cli_7.2.1_linux_amd64.tar.gz"
        sha256 "076216918764bbf7c5d764f1edc3a87b30901aa49963c60473b5c96e01736aa0"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.2.1/src-cli_7.2.1_linux_arm64.tar.gz"
        sha256 "1098c2391e98b38a4610aefa0cfb7d32c997d40b6529e785bb2b481bf96f3b29"

        def install
          bin.install "src"
        end
      end
    end
  end
end
