# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT502 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.2/src-cli_5.0.2_darwin_arm64.tar.gz"
      sha256 "62b454b5ec059837677aa081854357562793154705ac0954f94586ab788550e7"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.2/src-cli_5.0.2_darwin_amd64.tar.gz"
      sha256 "d867a390756e16274a5e8887e7c1f51e28476a6030748491aca1079472c68d1d"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.2/src-cli_5.0.2_linux_arm64.tar.gz"
      sha256 "57dd7609b3d088ad0b97862315204728c27fb0b7e93878cdaabe0d36ab976e63"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.0.2/src-cli_5.0.2_linux_amd64.tar.gz"
      sha256 "c45a5ddd75c9f99a0c1693bfed271b35cc33d40b23f2d2680c58282069fcaaca"

      def install
        bin.install "src"
      end
    end
  end
end
