# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCli < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "3.29.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/3.29.3/src-cli_3.29.3_darwin_amd64.tar.gz"
      sha256 "5b20e2f33cd26fc1d40d5bddcb961d0d4cd4e20f1abb68f8052a0f23fc91927a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/3.29.3/src-cli_3.29.3_linux_amd64.tar.gz"
      sha256 "ae17446b6a15d1b0ca02c9dee8b28ca695bf8f84e935af7b8e1e204356eb7ae9"
    end
  end

  def install
    bin.install "src"
  end
end
