# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT512 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "5.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.2/src-cli_5.1.2_darwin_arm64.tar.gz"
      sha256 "313af7120feca0b9d756679e44c06360269ef724dd70d2ff3ee30c56ee9a12c1"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.2/src-cli_5.1.2_darwin_amd64.tar.gz"
      sha256 "2d010624f10e8101f92b17ee57a82648ed55eef4fd4aadff1133ae456e0abce2"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.2/src-cli_5.1.2_linux_arm64.tar.gz"
      sha256 "f01db0001162a611d506eef8a67a367b333eefdbb605ee2c0d2ec3243bd48af8"

      def install
        bin.install "src"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sourcegraph/src-cli/releases/download/5.1.2/src-cli_5.1.2_linux_amd64.tar.gz"
      sha256 "b0ab49597008943d8477039e5a8ef62cb8d25daceb9da9bae924a37b6addc5c2"

      def install
        bin.install "src"
      end
    end
  end
end
