# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcCliAT711 < Formula
  desc "Sourcegraph CLI"
  homepage "https://sourcegraph.com/"
  version "7.1.1"

  on_macos do
    on_intel do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.1/src-cli_7.1.1_darwin_amd64.tar.gz"
      sha256 "bc527182c8dc657d9be39aed1b098af9e51de33620c84688fd8bf35da8a01fd9"

      def install
        bin.install "src"
      end
    end
    on_arm do
      url "https://github.com/sourcegraph/src-cli/releases/download/7.1.1/src-cli_7.1.1_darwin_arm64.tar.gz"
      sha256 "24ce6bfb4981cb0223d1b59ed13240e30d7bd318ce06432715e5e5209433fc31"

      def install
        bin.install "src"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.1/src-cli_7.1.1_linux_amd64.tar.gz"
        sha256 "465ce576864351bada199d63594e2381eb2a8ee89f6b85f09e5bf5be63c47ef1"

        def install
          bin.install "src"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourcegraph/src-cli/releases/download/7.1.1/src-cli_7.1.1_linux_arm64.tar.gz"
        sha256 "f2b6d49a8baf3d4bc7c150449ae544655dbcd6b44ed565fc10aa8b343687f4d5"

        def install
          bin.install "src"
        end
      end
    end
  end
end
